image: docker:latest

before_script:
  - export ANSIBLE_VERSION=$(ansible --version | head -n 1 | awk -F " " '{print $2}')

stages:
  - build

.build_docker_image:
  stage: build
  tags:
    - docker
  services: ["docker:dind"]
  before_script:
    - echo -n $DOCKER_PASSWORD | docker login -u tektosoft --password-stdin
  script:
    - docker build -t tektosoft/ansible:$IMAGE_TAG -f Dockerfile .
  after_script:
    - docker push tektosoft/ansible

build:latest:
  extends: .build_docker_image
  variables:
    IMAGE_TAG: latest

build:fixversion:
  extends: .build_docker_image
  variables:
    IMAGE_TAG: $ANSIBLE_VERSION