image: docker:latest

stages:
  - build

.build_docker_image:
  stage: build
  tags:
    - docker
  services: ["docker:dind"]
  script:
    - echo -n $DOCKER_PASSWORD | docker login -u tektosoft --password-stdin
    - docker build -t tektosoft/ansible:$IMAGE_TAG -f Dockerfile .
  after_script:
    - docker push tektosoft/ansible

build latest:
  extends: .build_docker_image
  variables:
    IMAGE_TAG: latest

build fixed version:
  extends: .build_docker_image
  before_script:
    - export IMAGE_TAG=$(ansible --version | head -n 1 | awk -F " " '{print $2}')