image: docker:latest

stages:
  - build

.build_docker_image:
  stage: build
  tags:
    - docker
  services: ["docker:dind"]
  script:
    - echo -n $DOCKER_PASSWORD | docker login -u tektosoft --password-stdin
    - docker build -t tektosoft/ansible:$IMAGE_TAG -f Dockerfile .
  after_script:
    - docker push tektosoft/ansible

build latest:
  extends: .build_docker_image
  variables:
    IMAGE_TAG: latest

build fixed version:
  extends: .build_docker_image
  before_script:
    - export IMAGE_TAG=$(wget -q -O - http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/bionic/main/source/Sources.gz | gunzip |head -n 3|tail -1|awk -F " |-" '{print $2}')